### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by sgrove** [FormidableLabs/next-urql#10]
This is almost certainly me and my lack of experience with Next.js:

I have a working reasonml/next-js site, and I'm trying to add in reason-urql, but I'm hitting this error:

```
/Users/s/code/nextjs-default/node_modules/wonka/src/wonka.js:3
import * as WonkaJs from "./web/wonkaJs.js";
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.wonka/src/wonka.js (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:5192:18)
    at __webpack_require__ (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:23:31)
    at Module../node_modules/reason-urql/src/UrqlClient.bs.js (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:4247:76)
    at __webpack_require__ (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:23:31)
    at Module../node_modules/reason-urql/src/ReasonUrql.bs.js (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:4172:75)
    at __webpack_require__ (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/items.bs.js (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:4822:90)
    at __webpack_require__ (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.bs.js (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:4730:70)
    at __webpack_require__ (/Users/s/code/nextjs-default/.next/server/static/development/pages/index.js:23:31)
```

It's probably not related, given the stacktrace, but my initial sketch of the bindings are very simple:
```
type urqlClient('a) = 'a => React.element;

type withUrqlClient = {url: string};

[@bs.module "next-urql"]
external withUrqlClient: withUrqlClient => urqlClient('a) = "withUrqlClient";
```

I'm happy to provide any additional information I can to help sort this out. I'm working off of https://github.com/ryyppy/nextjs-default as a starting point!

**Comment by sgrove** [comment]
This was caused by a dependency (`wonka` in this case) only being shipped in es6, but next not transpiling it. Adding it to the list of modules to transpile fixed it up!
